### PR TITLE
Only log to slack on latest job

### PR DESCRIPTION
**Pull request by fernandolucchesi**

### CODE REVIEW

**Comment by nilsml** [comment]
Have you tested it with different cases?

**Comment by fernandolucchesi** [comment]
> Have you tested it with different cases?

created on a different branch to perform tests, not working yet... will convert do draft PR

**Comment by nilsml** [comment]
Remember that this is not a high priority task. That is why I put it far down in the todo column. Do not spend much time on it.

**Review by w3bdesign — APPROVED** [review]

**Comment by nilsml** [comment]
Should we just close this @fernandolucchesi ?

**Pull request closed without merging**
