### PR TITLE
♻️ Refactor dockerfile and upgrade next #1128

### PR DESCRIPTION
**Pull request by fernandolucchesi**

### CODE REVIEW

**Review by nilsml — COMMENTED** [review]
I can't really see how this change will reduce the file size, but seems like the Dockerfile is more tidy! I guess it is the nod_modules. Will test tomorrow on my local PC, and maybe you we can look at the PR together @fernandolucchesi ?

**Comment by SvSven** [comment]
We're still installing the dependencies using pnpm, so not sure if this will do anything with the theory that pnpm is the/one of the culprits in the crash loop. I doubt that calling the `next build` command from yarn, npm, or pnpm makes any difference.

Also this is most likely what reduces the image size so much @nilsml https://nextjs.org/docs/advanced-features/output-file-tracing

Overall it looks a lot cleaner, but I don't have enough experience with docker to spot any potential issues 😅

**Comment by fernandolucchesi** [comment]
> I can't really see how this change will reduce the file size, but seems like the Dockerfile is more tidy! I guess it is the nod_modules. Will test tomorrow on my local PC, and maybe you we can look at the PR together @fernandolucchesi ?

the trick is in this new feature by next: https://nextjs.org/docs/advanced-features/output-file-tracing
image

it generates a very optimised built version to run in a container. Then we can disregard the node_modules and a bunch of other files

**Comment by fernandolucchesi** [comment]
> We're still installing the dependencies using pnpm, so not sure if this will do anything with the theory that pnpm is the/one of the culprits in the crash loop. I doubt that calling the `next build` command from yarn, npm, or pnpm makes any difference.
> 
> Also this is most likely what reduces the image size so much @nilsml https://nextjs.org/docs/advanced-features/output-file-tracing
> 
> Overall it looks a lot cleaner, but I don't have enough experience with docker to spot any potential issues 😅

The dockerfile is using 3 "computers" (4 if you count dynatrace...)

deps: uses pnpm to install dependencies
build: doesn't use pnpm
run: doesn't use pnpm

the image is create from the runner container, which doesn't contain pnpm... differently from before

**Review by nilsml — APPROVED** [review]
Will be interesting to test it out. Only deploying the files that are needed should be a good thing, and we may pray to the gods that the crash loops will vanish too.

**Pull request merged**
