### PR TITLE
✨ Allow home page path inside routes

### PR DESCRIPTION
**Pull request by fernandolucchesi**

### CODE REVIEW

**Comment by fernandolucchesi** [comment]
@SvSven since you've coded this, could you please check if the changes I made to `web/lib/queryFromSlug.ts` will have any  unexpected side effects?

**Comment by SvSven** [comment]
It's been 8 months, so your guess is as good as mine 😅
I do believe that case was meant to handle the home page, I'm guessing that the default case in the switch there will now be triggered instead, and that the value of `slug` would be `['/']`? In which case it _should_ work?

Other than that - I checked out the PR locally to test it, but I don't fully understand how to make a home page? Do I just make a new route, select the relevant content and then manually add `/` in the "Complete URL for this page" field like below?

image

Because that didn't work, I'm still getting the content from AEM.
It doesn't seem like it would be very intuitive to a non-technical user either.

**Comment by wenche** [comment]
Remember [this issue](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/308) we don't actually want to manipulate this field directly (but we could revisit this later on)

**Comment by fernandolucchesi** [comment]
> It's been 8 months, so your guess is as good as mine 😅 I do believe that case was meant to handle the home page, I'm guessing that the default case in the switch there will now be triggered instead, and that the value of `slug` would be `['/']`? In which case it _should_ work?
> 
> Other than that - I checked out the PR locally to test it, but I don't fully understand how to make a home page? Do I just make a new route, select the relevant content and then manually add `/` in the "Complete URL for this page" field like below?
> 
> image
> 
> Because that didn't work, I'm still getting the content from AEM. It doesn't seem like it would be very intuitive to a non-technical user either.

From what I can see in the code the static pages are fetched with priority compared to the studio ones. In a different dataset it does work. If this is not the intended behaviour we need to change more logic in the web app

**Comment by fernandolucchesi** [comment]
Hi @BirteThornquist, could you please check this issue from an UX perspective? Do you have any good suggestions on how should we approach the home pages?

**Comment by BirteThornquist** [comment]
Hi @fernandolucchesi. I think the homepage should be separated and stand out from the rest of the route structure, placed at the very top and be called "Homepage". It should have its own icon as well. Like this maybe:
Skjermbilde 2022-01-13 kl  09 52 33
What do you think?

**Comment by fernandolucchesi** [comment]
> Hi @fernandolucchesi. I think the homepage should be separated and stand out from the rest of the route structure, placed at the very top and be called "Homepage". It should have its own icon as well. Like this maybe: Skjermbilde 2022-01-13 kl 09 52 33 What do you think?

I really like this approach for the homepage 👍

**Pull request closed without merging**
