### PR TITLE
🎨 Add media plugin #1840

### PR DESCRIPTION
**Pull request by padms**

### CODE REVIEW

**Review by fernandolucchesi — APPROVED** [review]
Good job!

**Comment by meols** [comment]
Thanks @padms - one question; can we have the dark background back as well? (better for accessibility/Trude's eye sight) :smile: Otherwise is this approved.

**Comment by padms** [comment]
@meols  You can switch to dark theme anytime. [Private Zenhub Image]([Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajR0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c254a24bf02d7b89ebe167fad05d4501249b03c/image.png)

**Comment by meols** [comment]
Great! Thanks! Approved! :thumbsup:

**Pull request merged**
